title: Muhammad Daniyal
logo:
description:
Web Developer
<br><br>
<a href="mailto:danyalkhan59@gmail.com"></a>
<br>
<a href="https://www.linkedin.com/in/muhammad-daniyal-841215144/">Linked In Profile</a>
